-- exercice 1
SELECT DISTINCT p.PNAME
FROM p
WHERE p.PNAME LIKE '%c%';

-- exercice 2
SELECT DISTINCT p.PNAME
FROM p
WHERE (p.WEIGHT * 454) <= 6000;

-- exercice 3
SELECT DISTINCT j.JNAME
FROM j
WHERE j.JNAME LIKE '%i%';

-- exercice 4
SELECT DISTINCT s.SNAME
FROM s
WHERE s.SNAME LIKE 'a%' OR s.SNAME LIKE '%c';

-- exercice 5
SELECT DISTINCT s.SNAME
FROM s
    JOIN spj on s.ID_S = spj.ID_S
WHERE YEAR(spj.DATE_DERNIERE_LIVRAISON) BETWEEN 2015 and 2019;